name: Release

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  crank:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: crank
            asset_name: crank-linux-amd64
            release_name: crank-linux
          - os: macos-latest
            artifact_name: crank
            asset_name: crank-macos-amd64
            release_name: crank-macos

    steps:
      - uses: actions/checkout@v2

      - name: Install libudev-dev
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install libudev-dev
          fi

      - name: Build
        run: |
          cd crank
          cargo build --release --locked

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: crank/target/release/crank
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          release_name: ${{ matrix.release_name }}

  dex:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: serum-dex
            asset_name: serumdex-linux-amd64
            release_name: serumdex-linux
          - os: macos-latest
            artifact_name: serum-dex
            asset_name: serumdex-macos-amd64
            release_name: serumdex-macos

    steps:
      - uses: actions/checkout@v2

      - name: Install libudev-dev
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install libudev-dev
          fi

      - name: Build
        run: ./do.sh build dex
      
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dex/target/bpfel-unknown-unknown/release/serum_dex.so
          asset_name: ${{ matrix.asset_name }}
          release_name: ${{ matrix.release_name }}
          tag: ${{ github.ref }}
