name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  crank:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install libudev-dev
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install libudev-dev
          fi

      - name: Build
        run: |
          cd crank
          cargo build --release --locked

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/crank
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dex:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install libudev-dev
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install libudev-dev
          fi

      - name: Build
        run: ./do.sh build dex

      - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dex/target/bpfel-unknown-unknown/release/serum_dex.so
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
